const keys = [
  {
    symbol: '`',
    symbolShift: '~',
    symbolRus: 'ё',
    symbolRusShift: 'Ё',
    size: 'btn__small',
    code: 'Backquote',
  },
  {
    symbol: '1',
    symbolShift: '!',
    symbolRus: '1',
    symbolRusShift: '!',
    size: 'btn__small',
    code: 'Digit1',
  },
  {
    symbol: '2',
    symbolShift: '@',
    symbolRus: '2',
    symbolRusShift: '"',
    size: 'btn__small',
    code: 'Digit2',
  },
  {
    symbol: '3',
    symbolShift: '#',
    symbolRus: '3',
    symbolRusShift: '№',
    size: 'btn__small',
    code: 'Digit3',
  },
  {
    symbol: '4',
    symbolShift: '$',
    symbolRus: '4',
    symbolRusShift: ';',
    size: 'btn__small',
    code: 'Digit4',
  },
  {
    symbol: '5',
    symbolShift: '%',
    symbolRus: '5',
    symbolRusShift: '%',
    size: 'btn__small',
    code: 'Digit5',
  },
  {
    symbol: '6',
    symbolShift: '^',
    symbolRus: '6',
    symbolRusShift: ':',
    size: 'btn__small',
    code: 'Digit6',
  },
  {
    symbol: '7',
    symbolShift: '&',
    symbolRus: '7',
    symbolRusShift: '?',
    size: 'btn__small',
    code: 'Digit7',
  },
  {
    symbol: '8',
    symbolShift: '*',
    symbolRus: '8',
    symbolRusShift: '*',
    size: 'btn__small',
    code: 'Digit8',
  },
  {
    symbol: '9',
    symbolShift: '(',
    symbolRus: '9',
    symbolRusShift: '(',
    size: 'btn__small',
    code: 'Digit9',
  },
  {
    symbol: '0',
    symbolShift: ')',
    symbolRus: '0',
    symbolRusShift: ')',
    size: 'btn__small',
    code: 'Digit0',
  },
  {
    symbol: '-',
    symbolShift: '_',
    symbolRus: '-',
    symbolRusShift: '_',
    size: 'btn__small',
    code: 'Minus',
  },
  {
    symbol: '=',
    symbolShift: '+',
    symbolRus: '=',
    symbolRusShift: '+',
    size: 'btn__small',
    code: 'Equal',
  },
  {
    symbol: 'Backspace',
    size: 'btn__backspace',
    code: 'Backspace',
  },
  {
    symbol: 'Tab',
    size: 'btn__medium',
    code: 'Tab',
  },
  {
    symbol: 'q',
    symbolShift: 'Q',
    symbolRus: 'й',
    symbolRusShift: 'Й',
    size: 'btn__small',
    code: 'KeyQ',
  },
  {
    symbol: 'w',
    symbolShift: 'W',
    symbolRus: 'ц',
    symbolRusShift: 'Ц',
    size: 'btn__small',
    code: 'KeyW',
  },
  {
    symbol: 'e',
    symbolShift: 'E',
    symbolRus: 'у',
    symbolRusShift: 'У',
    size: 'btn__small',
    code: 'KeyE',
  },
  {
    symbol: 'r',
    symbolShift: 'R',
    symbolRus: 'к',
    symbolRusShift: 'К',
    size: 'btn__small',
    code: 'KeyR',
  },
  {
    symbol: 't',
    symbolShift: 'T',
    symbolRus: 'е',
    symbolRusShift: 'Е',
    size: 'btn__small',
    code: 'KeyT',
  },
  {
    symbol: 'y',
    symbolShift: 'Y',
    symbolRus: 'н',
    symbolRusShift: 'Н',
    size: 'btn__small',
    code: 'KeyY',
  },
  {
    symbol: 'u',
    symbolShift: 'U',
    symbolRus: 'г',
    symbolRusShift: 'Г',
    size: 'btn__small',
    code: 'KeyU',
  },
  {
    symbol: 'i',
    symbolShift: 'I',
    symbolRus: 'ш',
    symbolRusShift: 'Ш',
    size: 'btn__small',
    code: 'KeyI',
  },
  {
    symbol: 'o',
    symbolShift: 'O',
    symbolRus: 'щ',
    symbolRusShift: 'Щ',
    size: 'btn__small',
    code: 'KeyO',
  },
  {
    symbol: 'p',
    symbolShift: 'P',
    symbolRus: 'з',
    symbolRusShift: 'З',
    size: 'btn__small',
    code: 'KeyP',
  },
  {
    symbol: '[',
    symbolShift: '{',
    symbolRus: 'х',
    symbolRusShift: 'Х',
    size: 'btn__small',
    code: 'BracketLeft',
  },
  {
    symbol: ']',
    symbolShift: '}',
    symbolRus: 'ъ',
    symbolRusShift: 'Ъ',
    size: 'btn__small',
    code: 'BracketRight',
  },
  {
    symbol: '\\',
    symbolShift: '|',
    symbolRus: '\\',
    symbolRusShift: '/',
    size: 'btn__small',
    code: 'Backslash',
  },
  {
    symbol: 'Del',
    size: 'btn__medium',
    code: 'Delete',
  },
  {
    symbol: 'Caps Lock',
    size: 'btn__long',
    code: 'CapsLock',
  },
  {
    symbol: 'a',
    symbolShift: 'A',
    symbolRus: 'ф',
    symbolRusShift: 'Ф',
    size: 'btn__small',
    code: 'KeyA',
  },
  {
    symbol: 's',
    symbolShift: 'S',
    symbolRus: 'ы',
    symbolRusShift: 'Ы',
    size: 'btn__small',
    code: 'KeyS',
  },
  {
    symbol: 'd',
    symbolShift: 'D',
    symbolRus: 'в',
    symbolRusShift: 'В',
    size: 'btn__small',
    code: 'KeyD',
  },
  {
    symbol: 'f',
    symbolShift: 'F',
    symbolRus: 'а',
    symbolRusShift: 'А',
    size: 'btn__small',
    code: 'KeyF',
  },
  {
    symbol: 'g',
    symbolShift: 'G',
    symbolRus: 'п',
    symbolRusShift: 'П',
    size: 'btn__small',
    code: 'KeyG',
  },
  {
    symbol: 'h',
    symbolShift: 'H',
    symbolRus: 'р',
    symbolRusShift: 'Р',
    size: 'btn__small',
    code: 'KeyH',
  },
  {
    symbol: 'j',
    symbolShift: 'J',
    symbolRus: 'о',
    symbolRusShift: 'О',
    size: 'btn__small',
    code: 'KeyJ',
  },
  {
    symbol: 'k',
    symbolShift: 'K',
    symbolRus: 'л',
    symbolRusShift: 'Л',
    size: 'btn__small',
    code: 'KeyK',
  },
  {
    symbol: 'l',
    symbolShift: 'L',
    symbolRus: 'д',
    symbolRusShift: 'Д',
    size: 'btn__small',
    code: 'KeyL',
  },
  {
    symbol: ';',
    symbolShift: ':',
    symbolRus: 'ж',
    symbolRusShift: 'Ж',
    size: 'btn__small',
    code: 'Semicolon',
  },
  {
    symbol: '\'',
    symbolShift: '"',
    symbolRus: 'э',
    symbolRusShift: 'Э',
    size: 'btn__small',
    code: 'Quote',
  },
  {
    symbol: 'Enter',
    size: 'btn__long',
    code: 'Enter',
  },
  {
    symbol: 'Shift',
    size: 'btn__long',
    code: 'ShiftLeft',
  },
  {
    symbol: 'z',
    symbolShift: 'Z',
    symbolRus: 'я',
    symbolRusShift: 'Я',
    size: 'btn__small',
    code: 'KeyZ',
  },
  {
    symbol: 'x',
    symbolShift: 'X',
    symbolRus: 'ч',
    symbolRusShift: 'Ч',
    size: 'btn__small',
    code: 'KeyX',
  },
  {
    symbol: 'c',
    symbolShift: 'C',
    symbolRus: 'с',
    symbolRusShift: 'С',
    size: 'btn__small',
    code: 'KeyC',
  },
  {
    symbol: 'v',
    symbolShift: 'V',
    symbolRus: 'м',
    symbolRusShift: 'М',
    size: 'btn__small',
    code: 'KeyV',
  },
  {
    symbol: 'b',
    symbolShift: 'B',
    symbolRus: 'и',
    symbolRusShift: 'И',
    size: 'btn__small',
    code: 'KeyB',
  },
  {
    symbol: 'n',
    symbolShift: 'N',
    symbolRus: 'т',
    symbolRusShift: 'Т',
    size: 'btn__small',
    code: 'KeyN',
  },
  {
    symbol: 'm',
    symbolShift: 'M',
    symbolRus: 'ь',
    symbolRusShift: 'Ь',
    size: 'btn__small',
    code: 'KeyM',
  },
  {
    symbol: ',',
    symbolShift: '<',
    symbolRus: 'б',
    symbolRusShift: 'Б',
    size: 'btn__small',
    code: 'Comma',
  },
  {
    symbol: '.',
    symbolShift: '>',
    symbolRus: 'ю',
    symbolRusShift: 'Ю',
    size: 'btn__small',
    code: 'Period',
  },
  {
    symbol: '/',
    symbolShift: '?',
    symbolRus: '.',
    symbolRusShift: ',',
    size: 'btn__small',
    code: 'Slash',
  },
  {
    symbol: '&#9652;',
    size: 'btn__standard',
    code: 'ArrowUp',
  },
  {
    symbol: 'Shift',
    size: 'btn__long',
    code: 'ShiftRight',
  },
  {
    symbol: 'Ctrl',
    size: 'btn__medium',
    code: 'ControlLeft',
  },
  {
    symbol: 'Win',
    size: 'btn__medium',
    code: 'MetaLeft',
  },
  {
    symbol: 'Alt',
    size: 'btn__medium',
    code: 'AltLeft',
  },
  {
    symbol: '',
    size: 'btn__space',
    code: 'Space',
  },
  {
    symbol: 'Alt',
    size: 'btn__medium',
    code: 'AltRight',
  },
  {
    symbol: '&#9666;',
    size: 'btn__standard',
    code: 'ArrowLeft',
  },
  {
    symbol: '&#9662;',
    size: 'btn__standard',
    code: 'ArrowDown',
  },
  {
    symbol: '&#9656;',
    size: 'btn__standard',
    code: 'ArrowRight',
  },
  {
    symbol: 'Ctrl',
    size: 'btn__medium',
    code: 'ControlRight',
  },
];

export default keys;
